// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace UTimer.My
{
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {
        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        /* TODO ERROR: Skipped RegionDirectiveTrivia *//* TODO ERROR: Skipped IfDirectiveTrivia */
        private static bool addedHandler;
        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (MyProject.Application.SaveMySettingsOnExit)
            {
                MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia *//* TODO ERROR: Skipped EndRegionDirectiveTrivia */
        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int Startup
        {
            get
            {
                return Conversions.ToInteger(this["Startup"]);
            }

            set
            {
                this["Startup"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1")]
        public string MWAutoTime
        {
            get
            {
                return Conversions.ToString(this["MWAutoTime"]);
            }

            set
            {
                this["MWAutoTime"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("2")]
        public string AutoTimeBTBHour
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTBHour"]);
            }

            set
            {
                this["AutoTimeBTBHour"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTBMin
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTBMin"]);
            }

            set
            {
                this["AutoTimeBTBMin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTBSec
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTBSec"]);
            }

            set
            {
                this["AutoTimeBTBSec"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTTHour
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTTHour"]);
            }

            set
            {
                this["AutoTimeBTTHour"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("30")]
        public string AutoTimeBTTMin
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTTMin"]);
            }

            set
            {
                this["AutoTimeBTTMin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTTSec
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTTSec"]);
            }

            set
            {
                this["AutoTimeBTTSec"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("2")]
        public string AutoTimeBTB1Hour
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTB1Hour"]);
            }

            set
            {
                this["AutoTimeBTB1Hour"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTB1Min
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTB1Min"]);
            }

            set
            {
                this["AutoTimeBTB1Min"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeBTB1Sec
        {
            get
            {
                return Conversions.ToString(this["AutoTimeBTB1Sec"]);
            }

            set
            {
                this["AutoTimeBTB1Sec"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeTTHour
        {
            get
            {
                return Conversions.ToString(this["AutoTimeTTHour"]);
            }

            set
            {
                this["AutoTimeTTHour"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeTTMin
        {
            get
            {
                return Conversions.ToString(this["AutoTimeTTMin"]);
            }

            set
            {
                this["AutoTimeTTMin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeTTSec
        {
            get
            {
                return Conversions.ToString(this["AutoTimeTTSec"]);
            }

            set
            {
                this["AutoTimeTTSec"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeSh
        {
            get
            {
                return Conversions.ToString(this["AutoTimeSh"]);
            }

            set
            {
                this["AutoTimeSh"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeShHour
        {
            get
            {
                return Conversions.ToString(this["AutoTimeShHour"]);
            }

            set
            {
                this["AutoTimeShHour"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeShMin
        {
            get
            {
                return Conversions.ToString(this["AutoTimeShMin"]);
            }

            set
            {
                this["AutoTimeShMin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string AutoTimeShSec
        {
            get
            {
                return Conversions.ToString(this["AutoTimeShSec"]);
            }

            set
            {
                this["AutoTimeShSec"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int Sound1
        {
            get
            {
                return Conversions.ToInteger(this["Sound1"]);
            }

            set
            {
                this["Sound1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int Sound2
        {
            get
            {
                return Conversions.ToInteger(this["Sound2"]);
            }

            set
            {
                this["Sound2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Sound1Location
        {
            get
            {
                return Conversions.ToString(this["Sound1Location"]);
            }

            set
            {
                this["Sound1Location"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Sound2Location
        {
            get
            {
                return Conversions.ToString(this["Sound2Location"]);
            }

            set
            {
                this["Sound2Location"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("6")]
        public int DateFormat
        {
            get
            {
                return Conversions.ToInteger(this["DateFormat"]);
            }

            set
            {
                this["DateFormat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int TimeFormat
        {
            get
            {
                return Conversions.ToInteger(this["TimeFormat"]);
            }

            set
            {
                this["TimeFormat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool UpdateNeeded
        {
            get
            {
                return Conversions.ToBoolean(this["UpdateNeeded"]);
            }

            set
            {
                this["UpdateNeeded"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string NewVersion
        {
            get
            {
                return Conversions.ToString(this["NewVersion"]);
            }

            set
            {
                this["NewVersion"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("4")]
        public int DateFormat4Break
        {
            get
            {
                return Conversions.ToInteger(this["DateFormat4Break"]);
            }

            set
            {
                this["DateFormat4Break"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool AudioOrVisual
        {
            get
            {
                return Conversions.ToBoolean(this["AudioOrVisual"]);
            }

            set
            {
                this["AudioOrVisual"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool SetTimeOrBreak
        {
            get
            {
                return Conversions.ToBoolean(this["SetTimeOrBreak"]);
            }

            set
            {
                this["SetTimeOrBreak"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1")]
        public string MinWarnSh
        {
            get
            {
                return Conversions.ToString(this["MinWarnSh"]);
            }

            set
            {
                this["MinWarnSh"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool AudOrVis
        {
            get
            {
                return Conversions.ToBoolean(this["AudOrVis"]);
            }

            set
            {
                this["AudOrVis"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool BreaktimeUnlocked
        {
            get
            {
                return Conversions.ToBoolean(this["BreaktimeUnlocked"]);
            }

            set
            {
                this["BreaktimeUnlocked"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool BreaktimePaused
        {
            get
            {
                return Conversions.ToBoolean(this["BreaktimePaused"]);
            }

            set
            {
                this["BreaktimePaused"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool TimeChanged
        {
            get
            {
                return Conversions.ToBoolean(this["TimeChanged"]);
            }

            set
            {
                this["TimeChanged"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool ForShutdown
        {
            get
            {
                return Conversions.ToBoolean(this["ForShutdown"]);
            }

            set
            {
                this["ForShutdown"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool ForTimer
        {
            get
            {
                return Conversions.ToBoolean(this["ForTimer"]);
            }

            set
            {
                this["ForTimer"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool ForBTimer
        {
            get
            {
                return Conversions.ToBoolean(this["ForBTimer"]);
            }

            set
            {
                this["ForBTimer"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool ForAlarm
        {
            get
            {
                return Conversions.ToBoolean(this["ForAlarm"]);
            }

            set
            {
                this["ForAlarm"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Hardcored
        {
            get
            {
                return Conversions.ToBoolean(this["Hardcored"]);
            }

            set
            {
                this["Hardcored"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool FirstRun
        {
            get
            {
                return Conversions.ToBoolean(this["FirstRun"]);
            }

            set
            {
                this["FirstRun"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string NewVersionA
        {
            get
            {
                return Conversions.ToString(this["NewVersionA"]);
            }

            set
            {
                this["NewVersionA"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Black")]
        public Color ForeColor
        {
            get
            {
                return (Color)this["ForeColor"];
            }

            set
            {
                this["ForeColor"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("White")]
        public Color BackColor
        {
            get
            {
                return (Color)this["BackColor"];
            }

            set
            {
                this["BackColor"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Reminder1Recurrance
        {
            get
            {
                return Conversions.ToString(this["Reminder1Recurrance"]);
            }

            set
            {
                this["Reminder1Recurrance"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Reminder2Recurrance
        {
            get
            {
                return Conversions.ToString(this["Reminder2Recurrance"]);
            }

            set
            {
                this["Reminder2Recurrance"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Monday1
        {
            get
            {
                return Conversions.ToBoolean(this["Monday1"]);
            }

            set
            {
                this["Monday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Monday2
        {
            get
            {
                return Conversions.ToBoolean(this["Monday2"]);
            }

            set
            {
                this["Monday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Tuesday1
        {
            get
            {
                return Conversions.ToBoolean(this["Tuesday1"]);
            }

            set
            {
                this["Tuesday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Tuesday2
        {
            get
            {
                return Conversions.ToBoolean(this["Tuesday2"]);
            }

            set
            {
                this["Tuesday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Wednesday1
        {
            get
            {
                return Conversions.ToString(this["Wednesday1"]);
            }

            set
            {
                this["Wednesday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Wednesday2
        {
            get
            {
                return Conversions.ToBoolean(this["Wednesday2"]);
            }

            set
            {
                this["Wednesday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Thursday1
        {
            get
            {
                return Conversions.ToBoolean(this["Thursday1"]);
            }

            set
            {
                this["Thursday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Thursday2
        {
            get
            {
                return Conversions.ToBoolean(this["Thursday2"]);
            }

            set
            {
                this["Thursday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Friday1
        {
            get
            {
                return Conversions.ToBoolean(this["Friday1"]);
            }

            set
            {
                this["Friday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Friday2
        {
            get
            {
                return Conversions.ToBoolean(this["Friday2"]);
            }

            set
            {
                this["Friday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Saturday1
        {
            get
            {
                return Conversions.ToBoolean(this["Saturday1"]);
            }

            set
            {
                this["Saturday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Saturday2
        {
            get
            {
                return Conversions.ToBoolean(this["Saturday2"]);
            }

            set
            {
                this["Saturday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Sunday1
        {
            get
            {
                return Conversions.ToBoolean(this["Sunday1"]);
            }

            set
            {
                this["Sunday1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool Sunday2
        {
            get
            {
                return Conversions.ToBoolean(this["Sunday2"]);
            }

            set
            {
                this["Sunday2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderDay1
        {
            get
            {
                return Conversions.ToString(this["ReminderDay1"]);
            }

            set
            {
                this["ReminderDay1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderDay2
        {
            get
            {
                return Conversions.ToString(this["ReminderDay2"]);
            }

            set
            {
                this["ReminderDay2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderTime1
        {
            get
            {
                return Conversions.ToString(this["ReminderTime1"]);
            }

            set
            {
                this["ReminderTime1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderTime2
        {
            get
            {
                return Conversions.ToString(this["ReminderTime2"]);
            }

            set
            {
                this["ReminderTime2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderName1
        {
            get
            {
                return Conversions.ToString(this["ReminderName1"]);
            }

            set
            {
                this["ReminderName1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderName2
        {
            get
            {
                return Conversions.ToString(this["ReminderName2"]);
            }

            set
            {
                this["ReminderName2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderPic1
        {
            get
            {
                return Conversions.ToString(this["ReminderPic1"]);
            }

            set
            {
                this["ReminderPic1"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string ReminderPic2
        {
            get
            {
                return Conversions.ToString(this["ReminderPic2"]);
            }

            set
            {
                this["ReminderPic2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string BTSoundLocation
        {
            get
            {
                return Conversions.ToString(this["BTSoundLocation"]);
            }

            set
            {
                this["BTSoundLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool BTSoundIsDiff
        {
            get
            {
                return Conversions.ToBoolean(this["BTSoundIsDiff"]);
            }

            set
            {
                this["BTSoundIsDiff"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string BTSound
        {
            get
            {
                return Conversions.ToString(this["BTSound"]);
            }

            set
            {
                this["BTSound"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool UpdateIsSkipped
        {
            get
            {
                return Conversions.ToBoolean(this["UpdateIsSkipped"]);
            }

            set
            {
                this["UpdateIsSkipped"] = value;
            }
        }
    }
}

namespace UTimer.My
{
    [HideModuleName()]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal static class MySettingsProperty
    {
        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}